({
  title: req.body.title,
  image: req.file?.filename,
  petName: req.body.petName,
  species: req.body.species,
  breed: req.body.breed,
  sex: req.body.sex,
  size: req.body.size,
  age: req.body.age,
  medical: req.body.medical,
  isArchive: req.body.isArchive,
  favouritesCount: req.body.favouritesCount,
  ownerContactName: req.body.ownerContactName,
  ownerContactEmail: req.body.ownerContactEmail,
  ownerContactPhone: req.body.ownerContactPhone,
  ownerContactAddress: req.body.ownerContactAddress,
  profileContact: {
    // here links with payload from users /login
    id: req.decoded.id,
    name: req.decoded.name,
    email: req.decoded.email,
  },
  comments: req.body.comments,
  dateCreated: req.body.dateCreated,
});
